// Insurance companies, TPAs, government schemes, and corporate accounts the hospital bills
// treatment against. Kept as a plain list here (not admin-configurable yet) since it changes
// rarely — extend this array if a new panel needs to be added.
export const PANEL_OPTIONS = [
  "AYUSHMAN BHARAT",
  "HDFC ERGO GENERAL INSURANCE",
  "Universal Sompo General Insurance",
  "TATA AIG",
  "Go Digit",
  "ICICI LOMBARD GENERAL INSURANCE COMPANY LTD",
  "Care Health Insurance",
  "SBI GENERAL INSURANCE",
  "Reliance General Insurance Company",
  "Manipal Cigna",
  "THE NEW INDIA INSURANCE COMPANY",
  "Bajaj Allianz General Insurance",
  "NATIONAL INSURANCE",
  "UNITED INDIA INSURANCE",
  "THE ORIENTAL INSURANCE",
  "NIVA BUPA HEALTH INSURANCE",
  "Modern Civil Construction ( LLP)",
  "Raksha TPA",
  "Cash with (Package Medicine)",
  "NIVA BUPA",
  "PARAMOUNT TPA",
  "MEDI ASSIST",
  "Varun Beverages Ltd. Unit-2",
  "krishna buildestates pvt limited",
  "VIDAL HEALTH",
  "MD INDIA HEALTH INSURANCE TPA",
  "VIPUL MEDCORP/VIDAL HEALTH TPA",
  "PARK MEDICLAIM TPA",
  "FHPL TPA",
  "HEALTH INDIA INSURANCE TPA",
  "SAFEWAY INSURANCE TPA",
  "ERICSON INSURANCE TPA",
  "MEDVANTAGE INSURANCE TPA PVT. LTD. (UNITED HEALTHCARE PAREKH TPA)",
  "EAST WEST ASSIST INSURANCE",
  "MEDSAVE HEALTH INSURANCE TPA",
  "GOOD HEALTH INSURANCE TPA",
  "KENKO HEALTH INSURANCE",
  "GENINS INDIA INSURANCE TPA LTD",
  "Manipal Signa Health Insurance",
  "CAPF",
  "CGHS",
  "ESIC",
  "ECHS",
  "Cash",
  "Care Health Insurance.",
  "G.k Winding wires .Ltd- Geekay",
  "AYUSHMAN CAPF",
  "Delhi Police",
  "Aditya Birla",
  "Radnik Auto Export",
  "DIPTY LAL JUDGE MAL PVT. LTD.",
  "Food corporation of India",
];
